[package]
name = "demixer"
version = "0.7.5"
authors = ["Piotr Tarsa"]

[features]
default = []
long_tests = []

[profile.dev]
opt-level = 1

[profile.release]
lto = true

[profile.test]
opt-level = 1

[dependencies]
